version: '3'
services:
  experiment_manager:
    environment:
      experiment_manager_parameters: |
        episodes_per_scenario: 2
        episode_length_s: 1.0
        min_episode_length_s: 1.0
        seed: 20200922
        physics_dt: 0.05
        max_failures: 2
        agent_in: /fifos/agent-in
        agent_out: /fifos/agent-out
        sim_in: /fifos/simulator-in
        sim_out: /fifos/simulator-out
        sm_in: /fifos/scenario_maker-in
        sm_out: /fifos/scenario_maker-out
        timeout_initialization: 15
        timeout_regular: 30

    build:
      context: ./experiment_manager
    volumes: &volumes
      - ./challenges-dir:/challenges
      - fifos:/fifos
      - ${DT_ENV_DEVELOPER}/src/aido-protocols/src:/project/src/aido-protocols/src:ro
      - ${DT_ENV_DEVELOPER}/src/duckietown-world/src:/project/src/duckietown-world/src:ro
      - ${DT_ENV_DEVELOPER}/src/gym-duckietown:/project/src/gym-duckietown:ro
      - ${DT_ENV_DEVELOPER}/src/duckietown-challenges/src:/project/src/duckietown-challenges/src:ro
      #- ${DT_ENV_DEVELOPER}/src/zuper-nodes/src:/project/src/zuper-nodes/src:ro
      #- ${DT_ENV_DEVELOPER}/src/zuper-utils/src:/project/src/zuper-utils/src:ro
      #- ${DT_ENV_DEVELOPER}/src/zuper-commons/src:/project/src/zuper-commons/src:ro



  scenario_maker:
    environment:
      AIDONODE_DATA_IN: /fifos/scenario_maker-in
      AIDONODE_DATA_OUT: fifo:/fifos/scenario_maker-out
      AIDONODE_CONFIG: |
        maps:
        - ETHZ_autolab_technical_track
        - udem1
        scenarios_per_map: 5
        robots_npcs: 4
    build:
      context: ./scenario_maker
    volumes: *volumes
  simulator:
    build:
      context: ./simulator
    environment:
      AIDONODE_DATA_IN: /fifos/simulator-in
      AIDONODE_DATA_OUT: fifo:/fifos/simulator-out
      AIDONODE_CONFIG: |
        env_constructor: Simulator
        env_parameters:
          max_steps: 500001 # we don't want the gym to reset itself
          domain_rand: 0
          camera_width: 640
          camera_height: 480
          distortion: true
    volumes: *volumes

  solution:
    build:
      context: ./minimal_agent
    environment:
      AIDONODE_DATA_IN: /fifos/agent-in
      AIDONODE_DATA_OUT: fifo:/fifos/agent-out
    volumes: *volumes
volumes:
  fifos:
